# Dependencies
markdown:         kramdown
highlighter:      rouge

gems:
  - jekyll-redirect-from

# Permalinks
permalink:        pretty

# Setup
title:            The Security Setup
tagline:          'What setup do folks in security use to attack, defend, build, hack, crack, secure etc'
description:      ''
url:              http://thesecuritysetup.com
baseurl:          /
form:             '<a href="https://github.com/janfry/securitysetup/issues">here</a>'

author:
  name:           ''
  url:            https://twitter.com/securitysetup

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/janfry/thesecuritysetup
